GO

CREATE TABLE dbo.Medias(
	Id INT NOT NULL 
		CONSTRAINT PK_Medias_Id 
		PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(255) NOT NULL,
	Url VARCHAR(MAX) NOT NULL,
	RadioId INT NULL
		CONSTRAINT FK_Medias_Radios_RadioId 
		FOREIGN KEY REFERENCES dbo.Radios(Id),
	Status BIT NOT NULL DEFAULT 1
)

GO